database:
  adapter:  mysql
  charset:  utf8mb4
  encoding: utf8mb4
  database: augehorus_development
  username: coin_app
  password: test
  host:     127.0.0.1
  port:     3306
  pool:     5
  reconnect: true
  logFile: ./tmp/development_db.log
batch:
  logFile: ./tmp/development_batche.log
apiServer:
  logFile: ./tmp/development_api.log
  port: :5001
  pidFile: ./tmp/api_server.pid
appServer:
  logFile: ./tmp/development_app.log
  port: :5000
  pidFile: ./tmp/app_server.pid
