database:
  adapter:  mysql
  charset:  utf8mb4
  encoding: utf8mb4
  database: augehorus_test
  username: coin_app
  password: test
  host:     127.0.0.1
  port:     3306
  pool:     5
  reconnect: true
  logFile: ./tmp/test_db.log
