default: &default
  adapter:  <%= ENV["DB_ADAPTER"] %>
  database: <%= ENV["DB_DATABASE"] %>
  charset:  <%= ENV["DB_CHARSET"] %>
  encoding: <%= ENV["DB_ENCORDING"] %>
  username: <%= ENV["DB_USER_NAME"] %
  password: <%= ENV["DB_PASSWORD"] %>
  host:     <%= ENV["DB_HOST"] %>
  port:     <%= ENV["DB_PORT"] %>
  pool:     <%= ENV["DB_POOL"] %>
  reconnect: true

development:
  <<: *default

integration:
  <<: *default

test:
  <<: *default
