default: &default
  adapter:  mysql2
  charset:  utf8mb4
  encoding: utf8mb4
  username: coin_app
  password: test
  host:     127.0.0.1
  port:     3306
  pool:     5
  reconnect: true

development:
  <<: *default
  database: augehorus_development

integration:
  <<: *default
  database: augehorus_integration
  host:     10.0.2.10

test:
  <<: *default
  database: augehorus_test
